dienst2/templates/404.html, dienst2/templates/500.html, dienst2/templates/base.html, dienst2/templates/registration/login.html
HTTP error templates should allow us to disable debug in production
Should be tested first :grimacing:
=> Add 404 and 500 templates and set page titles

dienst2/extras.py, ldb/migrations/0002_nulls.py, ldb/migrations/0003_uniqueness.py, ldb/models.py
Fixes #43
Voor de bonus heb ik in de productie db al een tiental dubbele personen verwijderd, dus migration zou goed moeten gaan.
=> Uniqueness

ldb/models.py, ldb/serializers.py
Needed for OIDC [standard](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) and [address](http://openid.net/specs/openid-connect-core-1_0.html#AddressClaim) claims, but is probably useful for export as well.
=> Add formatted name and address to v3 API

dienst2/settings.py, kas/admin.py, ldb/admin.py, post/admin.py, requirements.txt
https://github.com/jedie/django-reversion-compare
=> Add django-reversion-compare

ldb/management/commands/clean_persons.py
Runs full_clean (and possibly save) on `Person`s, `Member`s and `Student`s.
Related to #70
=> Added clean_persons command

ldb/admin.py, ldb/export.py, ldb/locale/nl/LC_MESSAGES/django.po, ldb/management/commands/clean_persons.py, ldb/migrations/0006_gratuated_to_enrolled.py, ldb/migrations/0007_person_membership_status.py, ldb/models.py, ldb/serializers.py, ldb/static/partials/ldb/export.html, ldb/static/partials/ldb/person.html, requirements.txt
Depends on #69 (and includes its commits, so merge that first)
Fixes #51
Related to #64
=> Member logic

ldb/templates/ldb/organization_detail.html, ldb/templates/ldb/person_detail.html
=> Added `tel:` anchors for phone numbers

README.md
Scheelt weer een half uur kloten bij het opzetten van een lokale server :wink:
=> Bower added to README

ldb/templates/ldb/results.html
=> Improve search results

ldb/search_indexes.py, ldb/templates/search/indexes/ldb/organization_address.txt, ldb/templates/search/indexes/ldb/organization_contact.txt, ldb/templates/search/indexes/ldb/organization_name.txt, ldb/templates/search/indexes/ldb/person_address.txt, ldb/templates/search/indexes/ldb/person_contact.txt, ldb/templates/search/indexes/ldb/person_name.txt, ldb/templates/search/indexes/ldb/person_text.txt, ldb/views.py
To get better and more relevant search results, important fields in the Person and Organization model (name, ldap username) now outweigh less important fields (address, contact details) in determining the relevance of an item.
Closes #90
=> Implement search boost

dienst2/settings.py, dienst2/templates/base_bootstrap3.html, dienst2/templates/registration/logged_out.html, dienst2/urls.py
Ik heb een logout knop toegevoegd, is best handig op bijvoorbeeld de kassa. Voor nu staat 'ie in de dropdown rechtsbovenin.
De uitlog view heb ik ook in de stijl van de rest gemaakt, is niet zo spannend. :) Let trouwens wel op dat 'dienst2' in de settings.INSTALLED_APPS naar boven is verplaatst, omdat anders altijd de default admin.logout view gebruikt wordt.
=> Logout view, button

dienst2/templates/base_bootstrap3.html
=> Show username

ldb/views.py
=> Save person one more time to determine membership_status

ldb/migrations/0009_organization_blank_name_prefix.py, ldb/models.py, ldb/templates/ldb/organization_detail.html
=> Allow blank organization.name_prefix.

ldb/models.py, ldb/templates/ldb/committeemembership_filter.html, ldb/views.py
=> Committee page improvements

ldb/templates/ldb/committeemembership_filter.html
Closes #105 since we decided allowing to add in the admin is good enough.
=> Add admin button to committee page

README.md, dienst2/local.py.example
As a quick note while setting up the environment, as I hadn't realised this while setting up mine.
=> Add note in README.md about login while in dev.

.travis.yml, Dockerfile, ldb/tests/test_membership_status.py, requirements.txt
=> Django 1.11

Dockerfile, dienst2/settings.py, docker-entrypoint.sh, requirements.txt
=> WhiteNoise

requirements.txt
=> Upgrade to Django 1.11.2

requirements.txt
https://www.djangoproject.com/weblog/2017/jul/01/bugfix-release/
=> Upgade to Django 1.11.3

.dockerignore, .travis.yml, Dockerfile, Dockerfile-dev, README.md, dienst2/local.py, dienst2/local.py.travis, dienst2/management/commands/createdevsuperuser.py, docker-compose.yml, docker-entrypoint-dev.sh
Running `docker-compose up` creates a full development environment. ~~The step to manually create `local.py` seems a bit silly now; maybe we should include a development `local.py` in the repository (but keep it in `.gitignore`)?~~
=> Set up Docker development environment

requirements.txt
Filter version for requires.io:
https://requires.io/features/
=> Update Elasticsearch line in requirements.txt

dienst2/templates/dienst2/dashboard.html, ldb/templates/ldb/person_detail.html
Userman access is based on the 'staff' group.
=> Fix Userman access control

docker-entrypoint.sh
=> Wait for Elasticsearch to start before indexing

dienst2/middleware.py, dienst2/settings.py, dienst2/urls.py, requirements.txt
=> Add django-health-check at `/healthz`

dienst2/urls.py, dienst2/wsgi.py
Fixes distributed tracing with monkeypatch from https://github.com/DataDog/dd-trace-py/issues/456:
=> Datadog distributed tracing monkeypatch

dienst2/wsgi.py
=> Revert "Monkeypatch Datadog distributed tracing"

.travis.yml, dienst2/auth.py, dienst2/settings.py, package.json, requirements.txt, yarn.lock
=> Misc updates

dienst2/settings.py, ldb/serializers.py, ldb/viewsets.py, requirements.txt
=>  Add write support in API v3

ldb/templates/ldb/person_detail.html
=> Only diplay LDAP username link when it is set

ldb/templates/ldb/person_detail.html
@praseodym Ik kon er geen meer vinden dan dit?
=> Update link to userman2

ldb/management/commands/clean_persons.py
Ennn de laatste! Yay github editor.
=> Update dienst2 link

.github/workflows/deploy.yml
Changed structure of tags to (date)-(sha)
=> Change tags structure to only have one tag.

ldb/admin.py
This reverts commit a09bcccc7b4fc155b2ff29a3a8017589a09a5d67, reversing
changes made to de318782840ab052345dd6c2ee8be42f4fb0666d.
=> Revert "Merge pull request #283 from WISVCH/import-changes"

.github/workflows/deploy.yml
=> Log in to Quay only on master branch

ldb/views.py
=> Fix search

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .gitignore, .vscode/launch.json, .vscode/tasks.json, README.md, ci.env, dev.env
Allows convenient development setup in Visual Studio Code and GitHub
Codespaces.
Refer to the following websites for more information:
- https://containers.dev/
- https://docs.github.com/en/codespaces
- https://code.visualstudio.com/docs/devcontainers/containers
=> Add Dev Container configuration

ci.env, dev.env, dienst2/middleware.py, dienst2/settings.py, yarn.lock
Downgrade to CH bootstrap 3 theme.
Add dev auth. 
Accidentally in same branch.
=> Styling and Dev Auth
